---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "8.2"

  - name: install apache2 package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution in ["Ubuntu","Debian","CentOS"]

  - name: add php support for apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"
